### ISSUE TITLE
TypeError: pad_center() takes 1 positional argument but 2 were given

### ISSUE THREAD

**Issue by AbdullahMustafa040** [neosapience/mlp-singer#13]
```Traceback (most recent call last):
  File "/content/mlp-singer/inference.py", line 101, in <module>
    main(args)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/content/mlp-singer/inference.py", line 25, in main
    preprocessor = Preprocessor(preprocessor_config)
  File "/content/mlp-singer/data/preprocess.py", line 14, in __init__
    self.stft = TacotronSTFT(
  File "/content/mlp-singer/data/dsp/core.py", line 26, in __init__
    self.stft_fn = STFT(filter_length, hop_length, win_length)
  File "/content/mlp-singer/data/dsp/stft.py", line 66, in __init__
    fft_window = pad_center(fft_window, filter_length)
TypeError: pad_center() takes 1 positional argument but 2 were given```

**Comment by AbdullahMustafa040** [comment]
```
According to the documentation you provided, the pad_center function takes three required arguments: data, size, and axis. The data argument is the array to be padded, the size argument is the target length along the specified axis, and the axis argument specifies the axis along which to pad. The function also takes additional keyword arguments.

In your code snippet, you can update the line fft_window = pad_center(fft_window, filter_length) to correctly call the pad_center function with the required arguments. For example, you can change it to fft_window = pad_center(fft_window, size=filter_length) to specify the target size. If you want to pad along a specific axis, you can also provide the axis argument.

I hope this helps! Let me know if you have any further questions.
```



```
The error message you are seeing indicates that the mel function from the librosa.filters module is being called with 5 positional arguments, but it only takes keyword arguments. You can update the line mel_basis = librosa_mel_fn(sampling_rate, filter_length, n_mel_channels, mel_fmin, mel_fmax) to correctly call the mel function with the required keyword arguments. For example, you can change it to mel_basis = librosa_mel_fn(sr=sampling_rate, n_fft=filter_length, n_mels=n_mel_channels, fmin=mel_fmin, fmax=mel_fmax) to specify the required arguments using their keyword names.
```
